use super::*;
use crate::outputs_hid::{self, OutputBoard, MAX_LOOP_PULSES};
use std::path::PathBuf;

const DOF_GENERATOR_URL: &str = "https://configtool.vpuniverse.com/app/home";

/// Default output count for the Simulator backend. Matches a typical KL25Z
/// setup (22 outputs) so the UI feels realistic during dry-runs.
const SIMULATOR_DEFAULT_OUTPUTS: u16 = 22;

/// Copy-pasteable udev rules users can drop into /etc/udev/rules.d/ so
/// hidraw access to the Pinscape board works without root. Uses MODE=0666
/// (world-readable+writable) to match the DOF / pinball community convention
/// — simpler and more reliable across distros than `TAG+="uaccess"`, which
/// depends on systemd-logind's ACL support for hidraw (flaky in practice).
/// Pincabs are single-user appliances so the security trade-off is fine.
const UDEV_RULES_PINSCAPE: &str = "\
# /etc/udev/rules.d/99-pinscape.rules
# Pinscape KL25Z / Pico — USB + hidraw access for non-root users.
# Covers both LedWiz-emulation VID (FAFA) and private pid.codes (1209:EAEA).

# LedWiz emulation mode
SUBSYSTEM==\"usb\", ATTRS{idVendor}==\"fafa\", MODE=\"0666\"
SUBSYSTEM==\"hidraw\", ATTRS{idVendor}==\"fafa\", MODE=\"0666\"

# Private pid.codes (Pinscape Pico and KL25Z in private mode)
SUBSYSTEM==\"usb\", ATTRS{idVendor}==\"1209\", ATTRS{idProduct}==\"eaea\", MODE=\"0666\"
SUBSYSTEM==\"hidraw\", ATTRS{idVendor}==\"1209\", ATTRS{idProduct}==\"eaea\", MODE=\"0666\"
";

/// Folder libdof (integrated in VPX 10.8.1 standalone) reads its DOF config from.
/// The zip generated by configtool.vpuniverse.com must be extracted here.
/// Corresponds to `<base-path>/directoutputconfig/` with base-path =
/// VPinballX.ini's parent directory (per libdof's `GetBasePath`).
fn dof_config_dir() -> PathBuf {
    #[cfg(target_os = "linux")]
    {
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
        PathBuf::from(home).join(".local/share/VPinballX/10.8/directoutputconfig")
    }
    #[cfg(target_os = "macos")]
    {
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
        PathBuf::from(home).join("Library/Application Support/VPinballX/10.8/directoutputconfig")
    }
    #[cfg(target_os = "windows")]
    {
        let appdata = std::env::var("APPDATA").unwrap_or_else(|_| {
            let home = std::env::var("USERPROFILE").unwrap_or_else(|_| ".".into());
            format!("{home}\\AppData\\Roaming")
        });
        PathBuf::from(appdata).join("VPinballX\\10.8\\directoutputconfig")
    }
}

fn open_in_file_manager(path: &std::path::Path) {
    #[cfg(target_os = "linux")]
    let cmd = "xdg-open";
    #[cfg(target_os = "macos")]
    let cmd = "open";
    #[cfg(target_os = "windows")]
    let cmd = "explorer";

    if let Err(e) = std::process::Command::new(cmd).arg(path).spawn() {
        log::error!("Failed to open {}: {e}", path.display());
    }
}

impl App {
    pub(super) fn render_outputs_page(&mut self, ui: &mut egui::Ui) {
        ui.heading(t!("outputs_heading"));
        ui.add_space(4.0);
        ui.label(t!("outputs_desc"));
        ui.add_space(12.0);

        // --- Workflow steps ---
        ui.separator();
        ui.strong(t!("outputs_workflow_title"));
        ui.add_space(6.0);

        ui.label(format!("1. {}", t!("outputs_step1_account")));
        ui.label(format!("2. {}", t!("outputs_step2_table")));
        ui.label(format!("3. {}", t!("outputs_step3_output_system")));
        ui.label(format!("4. {}", t!("outputs_step4_devices")));
        ui.label(format!("5. {}", t!("outputs_step5_generate")));
        ui.label(format!("6. {}", t!("outputs_step6_extract")));
        ui.add_space(10.0);

        // --- Devices (non-exhaustive examples) ---
        ui.label(t!("outputs_devices_intro"));
        ui.add_space(2.0);
        ui.horizontal_wrapped(|ui| {
            for key in [
                "outputs_device_solenoids",
                "outputs_device_flashers",
                "outputs_device_gi",
                "outputs_device_rgb_buttons",
                "outputs_device_rgb_strips",
                "outputs_device_shaker",
                "outputs_device_knocker",
                "outputs_device_beacon",
                "outputs_device_gear",
            ] {
                ui.label(format!("• {}", t!(key)));
                ui.add_space(8.0);
            }
        });
        ui.add_space(12.0);

        // --- Web generator link ---
        ui.separator();
        ui.strong(t!("outputs_generator_title"));
        ui.add_space(4.0);
        ui.label(t!("outputs_generator_desc"));
        ui.add_space(4.0);
        ui.hyperlink_to(
            format!("🌐 {}", t!("outputs_open_generator")),
            DOF_GENERATOR_URL,
        );
        ui.add_space(12.0);

        // --- Local extraction target folder ---
        ui.separator();
        ui.strong(t!("outputs_target_title"));
        ui.add_space(4.0);
        ui.label(t!("outputs_target_desc"));
        ui.add_space(4.0);

        let dof_dir = dof_config_dir();
        ui.monospace(dof_dir.display().to_string());
        ui.add_space(6.0);

        let exists = dof_dir.is_dir();
        ui.horizontal(|ui| {
            let btn_label = format!("📁 {}", t!("outputs_open_folder"));
            if ui.button(btn_label).clicked() {
                if !exists {
                    if let Err(e) = std::fs::create_dir_all(&dof_dir) {
                        log::error!("Failed to create DOF config dir: {e}");
                    }
                }
                open_in_file_manager(&dof_dir);
            }

            if !exists {
                ui.colored_label(
                    egui::Color32::from_rgb(255, 180, 50),
                    t!("outputs_folder_missing"),
                );
            }
        });

        ui.add_space(16.0);
        self.render_output_discovery(ui);

        ui.add_space(16.0);
        self.render_dof_enable(ui);
    }

    /// DOF plugin activation switch. VPX standalone defaults every plugin to
    /// disabled — so even with a fully-working hardware + DOF config, the
    /// user sees nothing in-game until `[Plugin.DOF].Enable = 1` is written
    /// explicitly. This button writes it, after a clear safety acknowledgement
    /// that the DOF config has been generated and extracted.
    fn render_dof_enable(&mut self, ui: &mut egui::Ui) {
        ui.separator();
        ui.strong(t!("outputs_dof_enable_title"));
        ui.add_space(4.0);
        ui.label(t!("outputs_dof_enable_desc"));
        ui.add_space(8.0);

        let enabled = matches!(
            self.config.get("Plugin.DOF", "Enable").as_deref(),
            Some("1" | "true" | "on")
        );

        if enabled {
            ui.colored_label(
                egui::Color32::from_rgb(120, 220, 120),
                t!("outputs_dof_enable_status_on"),
            );
            ui.add_space(4.0);
            if ui.button(t!("outputs_dof_enable_disable")).clicked() {
                self.config.set("Plugin.DOF", "Enable", "");
                if let Err(e) = self.config.save() {
                    log::error!("Failed to save VPX ini after disabling DOF: {e}");
                }
            }
        } else {
            ui.colored_label(
                egui::Color32::from_rgb(255, 180, 50),
                t!("outputs_dof_enable_status_off"),
            );
            ui.add_space(4.0);
            if ui.button(t!("outputs_dof_enable_activate")).clicked() {
                self.config.set("Plugin.DOF", "Enable", "1");
                match self.config.save() {
                    Ok(()) => log::info!("[Plugin.DOF] Enable = 1 written to VPX ini"),
                    Err(e) => log::error!("Failed to save VPX ini after enabling DOF: {e}"),
                }
            }
        }
    }

    /// Output discovery tool: pulses each output so the user can map pin → device
    /// before filling in their DOF config on configtool.vpuniverse.com.
    fn render_output_discovery(&mut self, ui: &mut egui::Ui) {
        self.output_discovery.poll_events();
        self.output_discovery.poll_udev_apply();

        ui.separator();
        ui.strong(t!("outputs_discover_title"));
        ui.add_space(4.0);
        ui.label(t!("outputs_discover_desc"));
        ui.add_space(8.0);

        ui.colored_label(
            egui::Color32::from_rgb(255, 180, 50),
            t!("outputs_discover_safety"),
        );
        ui.add_space(8.0);

        if self.output_discovery.is_started() {
            self.render_discovery_session(ui);
        } else {
            self.render_discovery_start(ui);
        }
    }

    fn render_discovery_start(&mut self, ui: &mut egui::Ui) {
        ui.checkbox(
            &mut self.output_discovery.warning_ack,
            t!("outputs_discover_ack"),
        );
        ui.add_space(6.0);

        let can_start = self.output_discovery.warning_ack;

        // --- Hardware detection ---
        ui.horizontal(|ui| {
            let scan_label = if self.output_discovery.has_scanned {
                t!("outputs_discover_rescan")
            } else {
                t!("outputs_discover_scan")
            };
            if ui
                .add_enabled(can_start, egui::Button::new(scan_label))
                .clicked()
            {
                self.output_discovery.scan_hardware();
            }

            // Simulator is always available as a safe fallback for UX testing.
            if ui
                .add_enabled(
                    can_start,
                    egui::Button::new(t!("outputs_discover_start_simulator")),
                )
                .clicked()
            {
                let board: Box<dyn OutputBoard> =
                    Box::new(outputs_hid::Simulator::new(SIMULATOR_DEFAULT_OUTPUTS));
                self.output_discovery.start(board);
            }
        });
        ui.add_space(6.0);

        // --- Scan result ---
        if let Some(err) = self.output_discovery.detect_error.clone() {
            ui.colored_label(
                egui::Color32::from_rgb(255, 120, 120),
                t!("outputs_discover_scan_error", msg = err.clone()),
            );
            // Permission denied → one-click fix via polkit on Linux; fallback
            // to manual copy-paste on other platforms or if pkexec is missing.
            if err.to_lowercase().contains("permission") || err.to_lowercase().contains("access") {
                ui.add_space(4.0);
                self.render_udev_apply_controls(ui);
            }
        } else if self.output_discovery.has_scanned && self.output_discovery.detected.is_empty() {
            ui.colored_label(
                egui::Color32::from_rgb(255, 180, 50),
                t!("outputs_discover_scan_empty"),
            );
        }

        // Clone detected list so we can render + mutate state on click without
        // double-borrow issues.
        let detected = self.output_discovery.detected.clone();
        for board_info in detected {
            ui.add_space(4.0);
            ui.separator();
            ui.label(format!(
                "{}  —  VID {:04X} / PID {:04X}",
                board_info.kind.label(),
                board_info.vid,
                board_info.pid
            ));
            if !board_info.product.is_empty() {
                ui.weak(&board_info.product);
            }
            ui.weak(board_info.path_str());
            ui.add_space(4.0);

            // ConfigTool guidance block — pre-computed from USB VID/PID so the
            // user doesn't have to guess which controller entry to pick on
            // configtool.vpuniverse.com.
            egui::Frame::group(ui.style()).show(ui, |ui| {
                ui.strong(t!("outputs_discover_configtool_title"));
                ui.add_space(2.0);
                let mode = board_info.firmware_mode();
                if !mode.is_empty() {
                    ui.label(format!(
                        "{} {}",
                        t!("outputs_discover_configtool_firmware"),
                        mode
                    ));
                }
                ui.label(format!(
                    "{} {}",
                    t!("outputs_discover_configtool_controller"),
                    board_info.configtool_controller()
                ));
                if let Some(file) = board_info.expected_config_filename() {
                    ui.horizontal(|ui| {
                        ui.label(t!("outputs_discover_configtool_file"));
                        ui.monospace(&file);
                    });
                }
            });
            ui.add_space(4.0);

            if board_info.kind.has_driver() {
                if ui
                    .add_enabled(
                        can_start,
                        egui::Button::new(t!(
                            "outputs_discover_start_hardware",
                            n = board_info.num_outputs
                        )),
                    )
                    .clicked()
                {
                    match outputs_hid::open_board(
                        board_info.kind,
                        &board_info.path,
                        board_info.num_outputs,
                    ) {
                        Ok(board) => self.output_discovery.start(board),
                        Err(e) => {
                            self.output_discovery.detect_error = Some(e);
                        }
                    }
                }
            } else {
                // Detection works but we don't have a write driver yet —
                // user still gets the ConfigTool advice above. Disabled
                // button acts as documentation of the roadmap.
                ui.add_enabled(false, egui::Button::new(t!("outputs_discover_driver_soon")))
                    .on_disabled_hover_text(t!("outputs_discover_driver_soon_tooltip"));
            }
        }
    }

    /// Permission-denied remediation UI. On Linux shows a one-click pkexec
    /// button that installs the udev rules and auto-rescans on success. On
    /// other platforms (or if pkexec is missing) falls back to a Copy button
    /// for the manual path.
    fn render_udev_apply_controls(&mut self, ui: &mut egui::Ui) {
        #[cfg(target_os = "linux")]
        {
            // Auto-rescan when the install just completed successfully —
            // one-click flow: user clicks Install, types password, sees the
            // Pinscape row appear with no extra click.
            if matches!(self.output_discovery.udev_apply_status, Some(Ok(()))) {
                self.output_discovery.udev_apply_status = None;
                self.output_discovery.detect_error = None;
                self.output_discovery.scan_hardware();
                return;
            }

            let busy = self.output_discovery.udev_apply_rx.is_some();
            let label = if busy {
                t!("outputs_discover_apply_udev_busy")
            } else {
                t!("outputs_discover_apply_udev")
            };
            ui.horizontal(|ui| {
                if ui
                    .add_enabled(!busy, egui::Button::new(label))
                    .on_hover_text(t!("outputs_discover_apply_udev_tooltip"))
                    .clicked()
                {
                    let rx = crate::outputs_hid::spawn_udev_apply(UDEV_RULES_PINSCAPE.to_string());
                    self.output_discovery.udev_apply_rx = Some(rx);
                    self.output_discovery.udev_apply_status = None;
                }
                if busy {
                    ui.spinner();
                    ui.ctx().request_repaint();
                }
            });

            if let Some(Err(e)) = &self.output_discovery.udev_apply_status {
                ui.add_space(4.0);
                ui.colored_label(
                    egui::Color32::from_rgb(255, 120, 120),
                    t!("outputs_discover_apply_udev_err", msg = e.clone()),
                );
            }
        }

        // Non-Linux fallback: provide a copy-to-clipboard escape hatch. Rare
        // in practice (Windows/macOS don't need udev rules) but defensive.
        #[cfg(not(target_os = "linux"))]
        {
            if ui.button(t!("outputs_discover_copy_udev")).clicked() {
                ui.ctx().output_mut(|o| {
                    o.commands.push(egui::OutputCommand::CopyText(
                        UDEV_RULES_PINSCAPE.to_string(),
                    ))
                });
            }
        }
    }

    fn render_discovery_session(&mut self, ui: &mut egui::Ui) {
        let s = &self.output_discovery;
        ui.label(format!(
            "{} — {} {}",
            s.board_kind.label(),
            s.num_outputs,
            t!("outputs_discover_outputs_suffix")
        ));
        ui.add_space(6.0);

        ui.label(t!(
            "outputs_discover_status",
            n = s.current,
            total = s.num_outputs,
            pulse = s.pulse_count,
            max = MAX_LOOP_PULSES
        ));

        // Progress bar of the current loop's cycle count.
        let pct = (s.pulse_count as f32 / MAX_LOOP_PULSES as f32).clamp(0.0, 1.0);
        ui.add(egui::ProgressBar::new(pct).desired_width(300.0));
        ui.add_space(4.0);

        if !s.loop_running && s.pulse_count == 0 {
            ui.weak(t!("outputs_discover_idle"));
        } else if !s.loop_running && s.pulse_count >= MAX_LOOP_PULSES {
            ui.colored_label(
                egui::Color32::from_rgb(255, 180, 50),
                t!("outputs_discover_loop_complete", max = MAX_LOOP_PULSES),
            );
        }
        if let Some(err) = &s.last_error {
            ui.colored_label(
                egui::Color32::from_rgb(255, 120, 120),
                t!("outputs_discover_error", msg = err.clone()),
            );
        }
        ui.add_space(6.0);

        ui.horizontal(|ui| {
            if self.output_discovery.loop_running {
                if ui.button(t!("outputs_discover_pulse_stop")).clicked() {
                    self.output_discovery.stop_loop();
                }
            } else if ui.button(t!("outputs_discover_pulse_start")).clicked() {
                self.output_discovery.start_loop();
            }

            let can_replay = self.output_discovery.num_outputs > 0;
            if ui
                .add_enabled(can_replay, egui::Button::new(t!("outputs_discover_replay")))
                .clicked()
            {
                self.output_discovery.start_loop();
            }

            let can_prev = self.output_discovery.current > 1;
            if ui
                .add_enabled(can_prev, egui::Button::new(t!("outputs_discover_prev")))
                .clicked()
            {
                self.output_discovery.prev_output();
            }

            let can_next = self.output_discovery.current < self.output_discovery.num_outputs;
            if ui
                .add_enabled(can_next, egui::Button::new(t!("outputs_discover_next")))
                .clicked()
            {
                self.output_discovery.next_output();
            }
        });
        ui.add_space(8.0);

        // Label field for the currently-selected output.
        let current = self.output_discovery.current;
        ui.label(t!("outputs_discover_label_for", n = current));
        if let Some(label) = self.output_discovery.current_label_mut() {
            ui.add(
                egui::TextEdit::singleline(label)
                    .hint_text(t!("outputs_discover_label_placeholder"))
                    .desired_width(400.0),
            );
        }
        ui.add_space(12.0);

        // Summary of everything labelled so far.
        ui.strong(t!("outputs_discover_summary"));
        let summary = self.output_discovery.summary_text();
        if summary.is_empty() {
            ui.weak(t!("outputs_discover_summary_empty"));
        } else {
            ui.monospace(&summary);
        }
        ui.add_space(8.0);

        ui.horizontal(|ui| {
            if !summary.is_empty() && ui.button(t!("outputs_discover_copy")).clicked() {
                ui.ctx().output_mut(|o| {
                    o.commands
                        .push(egui::OutputCommand::CopyText(summary.clone()))
                });
            }
            if ui.button(t!("outputs_discover_end_session")).clicked() {
                self.output_discovery.stop_session();
                self.output_discovery = crate::outputs_hid::DiscoveryState::default();
            }
        });

        // Keep the UI repainting while the pulse loop is running so the
        // progress bar and counter stay fresh (otherwise egui only repaints
        // on input events, which would freeze the counter between clicks).
        if self.output_discovery.loop_running {
            ui.ctx().request_repaint();
        }
    }
}
