use super::*;
use std::path::PathBuf;

const DOF_GENERATOR_URL: &str = "https://configtool.vpuniverse.com/app/home";

/// Folder libdof (integrated in VPX 10.8.1 standalone) reads its DOF config from.
/// The zip generated by configtool.vpuniverse.com must be extracted here.
/// Corresponds to `<base-path>/directoutputconfig/` with base-path =
/// VPinballX.ini's parent directory (per libdof's `GetBasePath`).
fn dof_config_dir() -> PathBuf {
    #[cfg(target_os = "linux")]
    {
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
        PathBuf::from(home).join(".local/share/VPinballX/10.8/directoutputconfig")
    }
    #[cfg(target_os = "macos")]
    {
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
        PathBuf::from(home).join("Library/Application Support/VPinballX/10.8/directoutputconfig")
    }
    #[cfg(target_os = "windows")]
    {
        let appdata = std::env::var("APPDATA").unwrap_or_else(|_| {
            let home = std::env::var("USERPROFILE").unwrap_or_else(|_| ".".into());
            format!("{home}\\AppData\\Roaming")
        });
        PathBuf::from(appdata).join("VPinballX\\10.8\\directoutputconfig")
    }
}

fn open_in_file_manager(path: &std::path::Path) {
    #[cfg(target_os = "linux")]
    let cmd = "xdg-open";
    #[cfg(target_os = "macos")]
    let cmd = "open";
    #[cfg(target_os = "windows")]
    let cmd = "explorer";

    if let Err(e) = std::process::Command::new(cmd).arg(path).spawn() {
        log::error!("Failed to open {}: {e}", path.display());
    }
}

impl App {
    pub(super) fn render_outputs_page(&mut self, ui: &mut egui::Ui) {
        ui.heading(t!("outputs_heading"));
        ui.add_space(4.0);
        ui.label(t!("outputs_desc"));
        ui.add_space(12.0);

        // --- Workflow steps ---
        ui.separator();
        ui.strong(t!("outputs_workflow_title"));
        ui.add_space(6.0);

        ui.label(format!("1. {}", t!("outputs_step1_account")));
        ui.label(format!("2. {}", t!("outputs_step2_table")));
        ui.label(format!("3. {}", t!("outputs_step3_output_system")));
        ui.label(format!("4. {}", t!("outputs_step4_devices")));
        ui.label(format!("5. {}", t!("outputs_step5_generate")));
        ui.label(format!("6. {}", t!("outputs_step6_extract")));
        ui.add_space(10.0);

        // --- Devices (non-exhaustive examples) ---
        ui.label(t!("outputs_devices_intro"));
        ui.add_space(2.0);
        ui.horizontal_wrapped(|ui| {
            for key in [
                "outputs_device_solenoids",
                "outputs_device_flashers",
                "outputs_device_gi",
                "outputs_device_rgb_buttons",
                "outputs_device_rgb_strips",
                "outputs_device_shaker",
                "outputs_device_knocker",
                "outputs_device_beacon",
                "outputs_device_gear",
            ] {
                ui.label(format!("• {}", t!(key)));
                ui.add_space(8.0);
            }
        });
        ui.add_space(12.0);

        // --- Web generator link ---
        ui.separator();
        ui.strong(t!("outputs_generator_title"));
        ui.add_space(4.0);
        ui.label(t!("outputs_generator_desc"));
        ui.add_space(4.0);
        ui.hyperlink_to(
            format!("🌐 {}", t!("outputs_open_generator")),
            DOF_GENERATOR_URL,
        );
        ui.add_space(12.0);

        // --- Local extraction target folder ---
        ui.separator();
        ui.strong(t!("outputs_target_title"));
        ui.add_space(4.0);
        ui.label(t!("outputs_target_desc"));
        ui.add_space(4.0);

        let dof_dir = dof_config_dir();
        ui.monospace(dof_dir.display().to_string());
        ui.add_space(6.0);

        let exists = dof_dir.is_dir();
        ui.horizontal(|ui| {
            let btn_label = format!("📁 {}", t!("outputs_open_folder"));
            if ui.button(btn_label).clicked() {
                if !exists {
                    if let Err(e) = std::fs::create_dir_all(&dof_dir) {
                        log::error!("Failed to create DOF config dir: {e}");
                    }
                }
                open_in_file_manager(&dof_dir);
            }

            if !exists {
                ui.colored_label(
                    egui::Color32::from_rgb(255, 180, 50),
                    t!("outputs_folder_missing"),
                );
            }
        });
    }
}
